sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${CLOUD_TASTE_DB_HOST:localhost}
    port: ${CLOUD_TASTE_DB_PORT:3306}
    database: ${CLOUD_TASTE_DB_NAME:cloud_taste}
    username: ${CLOUD_TASTE_DB_USERNAME:root}
    password: ${CLOUD_TASTE_DB_PASSWORD:}
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID:}
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET:}
    bucket-name: java-lan
  redis:
    host: localhost
    port: 6379
    password:
    database: 2
